src/PWalnik.SDManager.Web/PWalnik.SDManager.Web/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PWalnik.SDManager.DataModel.Models;
using PWalnik.SDManager.Interfaces;

namespace PWalnik.SDManager.Web.Controllers
{
    [Authorize(Roles = "SalesRepresentative, Manager")]
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;

        public ClientController(IClientService clientService)
        {
            _clientService = clientService;
        }

        [HttpGet]
        public async Task<IActionResult>  Index(string currentFilter, string searchString, int? page)
        {
            if (searchString == null)
            {
                searchString = currentFilter;
            }
            else
            {
                page = 1;
            }
            ViewData["CurrentFilter"] = searchString;

            return View(await _clientService.GetAllClientsAsync(searchString, page));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyName, Country, Adress, City, PostalCode, Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                await _clientService.CreateAsync(customer);
                return RedirectToAction(nameof(Index));
            }

            return View(customer);
        }

        [HttpGet]
        public async Task<IActionResult>  Edit(int customerId)
        {
            return View(await _clientService.GetClientByIdAsync(customerId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                await _clientService.UpdateClientAsync(customer);
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _clientService.GetClientByIdAsync(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _clientService.DeleteClient(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/PWalnik.SDManager.Web/PWalnik.SDManager.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PWalnik.SDManager.DataModel.Models;
using PWalnik.SDManager.Interfaces;
using PWalnik.SDManager.Services.Requirements;

namespace PWalnik.SDManager.Web.Controllers
{
    [Authorize(Roles = "SalesRepresentative, Manager")]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IAuthorizationService _authorizationService;

        public OrderController(IOrderService orderService, IAuthorizationService authorizationService)
        {
            _orderService = orderService;
            _authorizationService = authorizationService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id, int? page)
        {
            if (!await _orderService.IsClientExists(id))
                return NotFound();

            ViewData["CustomerId"] = id;
            return View(await _orderService.GetAllOrdersAsync(id, page));
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
                return NotFound();

            if (!await _orderService.IsClientExists(id))
                return NotFound();

            Order order = new Order {CustomerId = id, EmployeeId = userId};
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Order order)
        {
            if (ModelState.IsValid)
            {
                await _orderService.AddNewOrderAsync(order);
                return RedirectToAction("Index", new {id = order.CustomerId});
            }
            return View(order);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (!await _orderService.IsOrderExists(id))
                return NotFound();

            var order = await _orderService.GetOrderByIdAsync(id);

            if (await _authorizationService.AuthorizeAsync(User, order, new EditOrderRequirement()))
            {
                return View(order);
            }

            return new ChallengeResult();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                await _orderService.UpdateOrderAsync(order);
                return RedirectToAction("Index", new {id = order.CustomerId});
            }
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!await _orderService.IsOrderExists(id))
                return NotFound();

            var order = await _orderService.GetOrderByIdAsync(id);

            if (await _authorizationService.AuthorizeAsync(User, order, new DeleteOrderRequirement()))
            {
                await _orderService.DeleteOrderAsync(order);
                return RedirectToAction("Index", new { id = order.CustomerId });
            }

            return new ChallengeResult();
        }
    }
}

src/PWalnik.SDManager.Web/PWalnik.SDManager.Web/Views/Client/Create.cshtml
@model PWalnik.SDManager.DataModel.Models.Customer


<br />
<form asp-controller="Client" asp-action="Create" method="post" class="form-horizontal">
    <h4>Add a new customer.</h4>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="CompanyName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="CompanyName" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Country" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Country" class="form-control" />
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Adress" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Adress" class="form-control" />
            <span asp-validation-for="Adress" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="City" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="PostalCode" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="PostalCode" class="form-control" />
            <span asp-validation-for="PostalCode" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Phone" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Add</button> | 
            <a asp-action="Index" class="btn btn-default">
                <span class="glyphicon glyphicon-home"></span>
            </a>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/PWalnik.SDManager.Web/PWalnik.SDManager.Web/Views/Client/Delete.cshtml
@model PWalnik.SDManager.DataModel.Models.Customer
@{
    ViewData["Title"] = "Delete";
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Company Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt>
            Adress
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adress),
            @Html.DisplayFor(model => model.PostalCode),
            @Html.DisplayFor(model => model.City),
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt>
            Phone
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    <input type="submit" value="Delete" class="btn btn-default" data-toggle="modal" data-target="#DeleteModal" />|
    <a asp-action="Index" class="btn btn-default">
        <span class="glyphicon glyphicon-home"></span>
    </a>

    <div id="DeleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <form asp-action="Delete">
                                <input type="submit" value="Yes" class="btn btn-success btn-block" />
                            </form>
                        </div>
                        <div class="col-sm-6">
                            <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/PWalnik.SDManager.Web/PWalnik.SDManager.Web/Views/Client/Edit.cshtml
@model PWalnik.SDManager.DataModel.Models.Customer

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CustomerId" />
        <div class="form-group">
            <label class="col-md-2 control-label">Company name</label>
            <div class="col-md-10">
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Country</label>
            <div class="col-md-10">
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Adress</label>
            <div class="col-md-10">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">City</label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Postal code</label>
            <div class="col-md-10">
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Phone</label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" /> |
                <a asp-action="Index" class="btn btn-default">
                    <span class="glyphicon glyphicon-home"></span>
                </a>
            </div>
        </div>
    </div>
</form>

src/PWalnik.SDManager.Web/PWalnik.SDManager.Web/Views/Client/Index.cshtml
@model PWalnik.SDManager.DataModel.ViewModels.PaginatedList<Customer>

@{
    ViewData["Title"] = "Index";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<br/>
<form asp-action="Index" method="get">
<div class="form-actions no-color">
    <p>
        Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
        <button type="submit" class="btn btn-default btn-md">
            <span class="glyphicon glyphicon-search"></span>
        </button> | 
        <a asp-action="Index" class="btn btn-default btn-md">
            <span class="glyphicon glyphicon-refresh"></span>
        </a> | 
        <a asp-action="Create" class="btn btn-custom">
            <span class="glyphicon glyphicon-plus"></span>
        </a>
    </p>
</div>
</form>


<table class="table table-striped" style="table-layout: fixed">
    <thead>
    <tr>
        <th>
            Company name
        </th>
        <th>
            Adress
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a asp-controller="Order" asp-action="Index" asp-route-id="@item.CustomerId" data-toggle="tooltip" title="Click to see all orders!">
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress), 
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                <a asp-action="Edit" asp-route-customerId="@item.CustomerId">Edit</a> | 
                <a asp-action="Delete" asp-route-id="@item.CustomerId">Delete</a> |
                <a asp-controller="Order" asp-action="Create" asp-route-id="@item.CustomerId">Add order</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<a asp-action="Index" asp-route-page="@(Model.PageIndex - 1)" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="btn btn-default @prevDisabled btn">
    <span class="glyphicon glyphicon-arrow-left"></span>
</a>
Page @Model.PageIndex of @Model.TotalPages
<a asp-action="Index" asp-route-page="@(Model.PageIndex + 1)" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="btn btn-default @nextDisabled btn">
    <span class="glyphicon glyphicon-arrow-right"></span>
</a>
Number of all clients: @Model.NumberOfItems